# This file was automatically generated by passthru.fetch-deps.
# Please dont edit it manually, your changes might get overwritten!

{ fetchNuGet }: [
  (fetchNuGet {
    pname = "Castle.Core";
    version = "5.1.1";
    sha256 = "1caf4878nvjid3cw3rw18p9cn53brfs5x8dkvf82xvcdwc3i0nd1";
  })
  (fetchNuGet {
    pname = "coverlet.collector";
    version = "6.0.2";
    sha256 = "0fll8yssdzi2wv8l26qz2zl0qqrp5nlbdqxjwfh5p356nd991m1d";
  })
  (fetchNuGet {
    pname = "Iot.Device.Bindings";
    version = "3.1.0";
    sha256 = "1985m18c6fhx8bnsigham9a5gijkw1ibdmnjicagf94cx5y90dvh";
  })
  (fetchNuGet {
    pname = "Microsoft.AspNetCore.App.Runtime.linux-arm64";
    version = "8.0.3";
    sha256 = "1s4lq0qiya5v73b5niipzmqkhj2d9wcb3nfaqlkbyjq660ahw98w";
  })
  (fetchNuGet {
    pname = "Microsoft.AspNetCore.App.Runtime.osx-arm64";
    version = "8.0.3";
    sha256 = "188bxir2v9rcfg036jmnczw3zlmf0kpy2f28jgbqli8ramlj5jq6";
  })
  (fetchNuGet {
    pname = "Microsoft.AspNetCore.App.Runtime.osx-x64";
    version = "8.0.3";
    sha256 = "0ri4jdv0v0pdwmvwgdzc46v43bd9d0xbbwscszqp8yd64dffs33v";
  })
  (fetchNuGet {
    pname = "Microsoft.CodeCoverage";
    version = "17.9.0";
    sha256 = "1gljgi69k0fz8vy8bn6xlyxabj6q4vls2zza9wz7ng6ix3irm89r";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.ApiDescription.Server";
    version = "6.0.5";
    sha256 = "1pi2bm3cm0a7jzqzmfc2r7bpcdkmk3hhjfvb2c81j7wl7xdw3624";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Configuration";
    version = "8.0.0";
    sha256 = "080kab87qgq2kh0ijry5kfdiq9afyzb8s0k3jqi5zbbi540yq4zl";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Configuration.Abstractions";
    version = "8.0.0";
    sha256 = "1jlpa4ggl1gr5fs7fdcw04li3y3iy05w3klr9lrrlc7v8w76kq71";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Configuration.Binder";
    version = "8.0.0";
    sha256 = "1m0gawiz8f5hc3li9vd5psddlygwgkiw13d7div87kmkf4idza8r";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Configuration.CommandLine";
    version = "8.0.0";
    sha256 = "026f7f2iv6ph2dc5rnslll0bly8qcx5clmh2nn9hgyqjizzc4qvy";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Configuration.EnvironmentVariables";
    version = "8.0.0";
    sha256 = "13qb8wz3k59ihq0mjcqz1kwrpyzxn5da4dhk2pvcgc42z9kcbf7r";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Configuration.FileExtensions";
    version = "8.0.0";
    sha256 = "1jrmlfzy4h32nzf1nm5q8bhkpx958b0ww9qx1k1zm4pyaf6mqb04";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Configuration.Json";
    version = "8.0.0";
    sha256 = "1n3ss26v1lq6b69fxk1vz3kqv9ppxq8ypgdqpd7415xrq66y4bqn";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Configuration.UserSecrets";
    version = "8.0.0";
    sha256 = "1br01zhzhnxjzqx63bxd25x48y9xs69hcs71pjni8y9kl50zja7z";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.DependencyInjection";
    version = "8.0.0";
    sha256 = "0i7qziz0iqmbk8zzln7kx9vd0lbx1x3va0yi3j1bgkjir13h78ps";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.DependencyInjection.Abstractions";
    version = "8.0.1";
    sha256 = "1wyhpamm1nqjfi3r463dhxljdlr6rm2ax4fvbgq2s0j3jhpdhd4p";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Diagnostics";
    version = "8.0.0";
    sha256 = "0ghwkld91k20hcbmzg2137w81mzzdh8hfaapdwckhza0vipya4kw";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Diagnostics.Abstractions";
    version = "8.0.0";
    sha256 = "15m4j6w9n8h0mj7hlfzb83hd3wn7aq1s7fxbicm16slsjfwzj82i";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.FileProviders.Abstractions";
    version = "8.0.0";
    sha256 = "1idq65fxwcn882c06yci7nscy9i0rgw6mqjrl7362prvvsd9f15r";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.FileProviders.Physical";
    version = "8.0.0";
    sha256 = "05wxjvjbx79ir7vfkri6b28k8zl8fa6bbr0i7gahqrim2ijvkp6v";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.FileSystemGlobbing";
    version = "8.0.0";
    sha256 = "1igf2bqism22fxv7km5yv028r4rg12a4lki2jh4xg3brjkagiv7q";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Hosting";
    version = "8.0.0";
    sha256 = "1f2af5m1yny8b43251gsj75hjd9ixni1clcldy8cg91z1vxxm8dh";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Hosting.Abstractions";
    version = "8.0.0";
    sha256 = "00d5dwmzw76iy8z40ly01hy9gly49a7rpf7k7m99vrid1kxp346h";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging";
    version = "8.0.0";
    sha256 = "0nppj34nmq25gnrg0wh1q22y4wdqbih4ax493f226azv8mkp9s1i";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging.Abstractions";
    version = "7.0.0";
    sha256 = "1gn7d18i1wfy13vrwhmdv1rmsb4vrk26kqdld4cgvh77yigj90xs";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging.Abstractions";
    version = "8.0.0";
    sha256 = "1klcqhg3hk55hb6vmjiq2wgqidsl81aldw0li2z98lrwx26msrr6";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging.Configuration";
    version = "8.0.0";
    sha256 = "1d9b734vnll935661wqkgl7ry60rlh5p876l2bsa930mvfsaqfcv";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging.Console";
    version = "8.0.0";
    sha256 = "1mvp3ipw7k33v2qw2yrvc4vl5yzgpk3yxa94gg0gz7wmcmhzvmkd";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging.Debug";
    version = "8.0.0";
    sha256 = "1h7mg97lj0ss47kq7zwnihh9c6xcrkwrr8ffhc16qcsrh36sg6q0";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging.EventLog";
    version = "8.0.0";
    sha256 = "05vfrxw7mlwlwhsl6r4yrhxk3sd8dv5sl0hdlcpgw62n53incw5x";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging.EventSource";
    version = "8.0.0";
    sha256 = "0gbjll6p03rmw0cf8fp0p8cxzn9awmzv8hvnyqbczrkax5h7p94i";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Options";
    version = "8.0.0";
    sha256 = "0p50qn6zhinzyhq9sy5svnmqqwhw2jajs2pbjh9sah504wjvhscz";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Options.ConfigurationExtensions";
    version = "8.0.0";
    sha256 = "04nm8v5a3zp0ill7hjnwnja3s2676b4wffdri8hdk2341p7mp403";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Primitives";
    version = "8.0.0";
    sha256 = "0aldaz5aapngchgdr7dax9jw5wy7k7hmjgjpfgfv1wfif27jlkqm";
  })
  (fetchNuGet {
    pname = "Microsoft.NET.Test.Sdk";
    version = "17.9.0";
    sha256 = "1lls1fly2gr1n9n1xyl9k33l2v4pwfmylyzkq8v4v5ldnwkl1zdb";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App.Host.linux-arm64";
    version = "8.0.3";
    sha256 = "1ck7pky6ks5qq294vlqjvxrdpi70xc1g0yhank9kb3vmx9ixm9li";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App.Host.osx-arm64";
    version = "8.0.3";
    sha256 = "03qrqwd5v9rvc15i26ik1jxy670xm3gl5qv6mmk0ii1b6qw97ckp";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App.Host.osx-x64";
    version = "8.0.3";
    sha256 = "1bpx1fkyd9dpfjb70l4gh73qvin7rimfrx2hsi1m2amqjmx88s6j";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App.Runtime.linux-arm64";
    version = "8.0.3";
    sha256 = "19cbqcbsmx2mx88b6xhyh08r16bl0pjq1c5vgj5ai63phs6hlsjp";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App.Runtime.osx-arm64";
    version = "8.0.3";
    sha256 = "0jnd22x6hi16c8q7l74kh6iqvpl0cbny3fcrrpqky38685n5nzw5";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App.Runtime.osx-x64";
    version = "8.0.3";
    sha256 = "0gk6082rr0fm3dzspwdqfjzhsbi02iym28r4kcyiy1wcx83z7dfq";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.Platforms";
    version = "5.0.0";
    sha256 = "0mwpwdflidzgzfx2dlpkvvnkgkr2ayaf0s80737h4wa35gaj11rc";
  })
  (fetchNuGet {
    pname = "Microsoft.OpenApi";
    version = "1.2.3";
    sha256 = "07b19k89whj69j87afkz86gp9b3iybw8jqwvlgcn43m7fb2y99rr";
  })
  (fetchNuGet {
    pname = "Microsoft.TestPlatform.ObjectModel";
    version = "17.9.0";
    sha256 = "1kgsl9w9fganbm9wvlkqgk0ag9hfi58z88rkfybc6kvg78bx89ca";
  })
  (fetchNuGet {
    pname = "Microsoft.TestPlatform.TestHost";
    version = "17.9.0";
    sha256 = "19ffh31a1jxzn8j69m1vnk5hyfz3dbxmflq77b8x82zybiilh5nl";
  })
  (fetchNuGet {
    pname = "Microsoft.Win32.Registry";
    version = "5.0.0";
    sha256 = "102hvhq2gmlcbq8y2cb7hdr2dnmjzfp2k3asr1ycwrfacwyaak7n";
  })
  (fetchNuGet {
    pname = "Microsoft.Win32.SystemEvents";
    version = "6.0.0";
    sha256 = "0c6pcj088g1yd1vs529q3ybgsd2vjlk5y1ic6dkmbhvrp5jibl9p";
  })
  (fetchNuGet {
    pname = "Moq";
    version = "4.20.70";
    sha256 = "0jzfxvw5ngxld2rfzq1361lqzi3f8shywqd4546ayz7wgga1vq9v";
  })
  (fetchNuGet {
    pname = "Newtonsoft.Json";
    version = "13.0.1";
    sha256 = "0fijg0w6iwap8gvzyjnndds0q4b8anwxxvik7y8vgq97dram4srb";
  })
  (fetchNuGet {
    pname = "OpenCvSharp4";
    version = "4.9.0.20240103";
    sha256 = "15mfqkyf32d4whzcnvqig064r22y8wr4babfpr6l55pin8anvf0x";
  })
  (fetchNuGet {
    pname = "RichardSzalay.MockHttp";
    version = "7.0.0";
    sha256 = "167r48r1mbjgq8wc9w7lhh63vy853sc2dvxjld372zh8mqi5aasz";
  })
  (fetchNuGet {
    pname = "runtime.linux-arm.runtime.native.System.IO.Ports";
    version = "8.0.0";
    sha256 = "0qgrgf155mgsnakh0pxfg41zfwfn5as16g91q4k355v1nrvsi7wv";
  })
  (fetchNuGet {
    pname = "runtime.linux-arm64.runtime.native.System.IO.Ports";
    version = "8.0.0";
    sha256 = "1clc032fbynp9f8f57fh11lk6k8y7g0nlyb9nm44a0zpfkfcc1i2";
  })
  (fetchNuGet {
    pname = "runtime.linux-x64.runtime.native.System.IO.Ports";
    version = "8.0.0";
    sha256 = "0l623wmc1kswkv76fv15s2l35c3j2a4jvbv0v5jl6wz1466jx2p3";
  })
  (fetchNuGet {
    pname = "runtime.native.System.IO.Ports";
    version = "8.0.0";
    sha256 = "13w1w8f9ky7h7fkc2vamjv4vvs6b7nb3mcz9zgl3w7pk9xak3886";
  })
  (fetchNuGet {
    pname = "runtime.osx-arm64.runtime.native.System.IO.Ports";
    version = "8.0.0";
    sha256 = "08a88k2ps72206pigjq47r3xvp2j1ncmrr82bzgjskxj9kmhalx0";
  })
  (fetchNuGet {
    pname = "runtime.osx-x64.runtime.native.System.IO.Ports";
    version = "8.0.0";
    sha256 = "1wbdzmcmp2fczv4c3pzvdbap9mnzrm2hp3gclshx0cm7rc6psqkg";
  })
  (fetchNuGet {
    pname = "Swashbuckle.AspNetCore";
    version = "6.5.0";
    sha256 = "0k61chpz5j59s1yax28vx0mppx20ff8vg8grwja112hfrzj1f45n";
  })
  (fetchNuGet {
    pname = "Swashbuckle.AspNetCore.Swagger";
    version = "6.5.0";
    sha256 = "1s6axf6fin8sss3bvzp0s039rxrx71vx4rl559miw12bz3lld8kc";
  })
  (fetchNuGet {
    pname = "Swashbuckle.AspNetCore.SwaggerGen";
    version = "6.5.0";
    sha256 = "0hq93gy5vyrigpdk9lhqwxglxwkbxa8ydllwcqs4bwfcsspzrs83";
  })
  (fetchNuGet {
    pname = "Swashbuckle.AspNetCore.SwaggerUI";
    version = "6.5.0";
    sha256 = "17hx7kc187higm0gk67dndng3n7932sn3fwyj48l45cvyr3025h7";
  })
  (fetchNuGet {
    pname = "System.CodeDom";
    version = "5.0.0";
    sha256 = "14zs2wqkmdlxzj8ikx19n321lsbarx5vl2a8wrachymxn8zb5njh";
  })
  (fetchNuGet {
    pname = "System.Device.Gpio";
    version = "3.1.0";
    sha256 = "0ldv1njm5sf7bvchdn9549vmckhdm7iig718rcn1yf54pxaqf32b";
  })
  (fetchNuGet {
    pname = "System.Diagnostics.DiagnosticSource";
    version = "8.0.0";
    sha256 = "0nzra1i0mljvmnj1qqqg37xs7bl71fnpl68nwmdajchh65l878zr";
  })
  (fetchNuGet {
    pname = "System.Diagnostics.EventLog";
    version = "6.0.0";
    sha256 = "08y1x2d5w2hnhkh9r1998pjc7r4qp0rmzax062abha85s11chifd";
  })
  (fetchNuGet {
    pname = "System.Diagnostics.EventLog";
    version = "8.0.0";
    sha256 = "1xnvcidh2qf6k7w8ij1rvj0viqkq84cq47biw0c98xhxg5rk3pxf";
  })
  (fetchNuGet {
    pname = "System.Drawing.Common";
    version = "6.0.0";
    sha256 = "02n8rzm58dac2np8b3xw8ychbvylja4nh6938l5k2fhyn40imlgz";
  })
  (fetchNuGet {
    pname = "System.IO.Pipelines";
    version = "7.0.0";
    sha256 = "1ila2vgi1w435j7g2y7ykp2pdbh9c5a02vm85vql89az93b7qvav";
  })
  (fetchNuGet {
    pname = "System.IO.Ports";
    version = "8.0.0";
    sha256 = "113vfqanh1fbxx264db2z207qkm02x7mnr854igkc1xb8xrzvj0v";
  })
  (fetchNuGet {
    pname = "System.Management";
    version = "5.0.0";
    sha256 = "09hyv3p0zd549577clydlb2szl84m4gvdjnsry73n8b12ja7d75s";
  })
  (fetchNuGet {
    pname = "System.Memory";
    version = "4.5.5";
    sha256 = "08jsfwimcarfzrhlyvjjid61j02irx6xsklf32rv57x2aaikvx0h";
  })
  (fetchNuGet {
    pname = "System.Reflection.Metadata";
    version = "1.6.0";
    sha256 = "1wdbavrrkajy7qbdblpbpbalbdl48q3h34cchz24gvdgyrlf15r4";
  })
  (fetchNuGet {
    pname = "System.Runtime.CompilerServices.Unsafe";
    version = "6.0.0";
    sha256 = "0qm741kh4rh57wky16sq4m0v05fxmkjjr87krycf5vp9f0zbahbc";
  })
  (fetchNuGet {
    pname = "System.Security.AccessControl";
    version = "5.0.0";
    sha256 = "17n3lrrl6vahkqmhlpn3w20afgz09n7i6rv0r3qypngwi7wqdr5r";
  })
  (fetchNuGet {
    pname = "System.Security.Principal.Windows";
    version = "5.0.0";
    sha256 = "1mpk7xj76lxgz97a5yg93wi8lj0l8p157a5d50mmjy3gbz1904q8";
  })
  (fetchNuGet {
    pname = "System.Text.Encodings.Web";
    version = "6.0.0";
    sha256 = "06n9ql3fmhpjl32g3492sj181zjml5dlcc5l76xq2h38c4f87sai";
  })
  (fetchNuGet {
    pname = "System.Text.Encodings.Web";
    version = "8.0.0";
    sha256 = "1wbypkx0m8dgpsaqgyywz4z760xblnwalb241d5qv9kx8m128i11";
  })
  (fetchNuGet {
    pname = "System.Text.Json";
    version = "6.0.1";
    sha256 = "0cxvkadvg0r0wh83k7677wvcjsfs2kifxvi7ia3ssvqplna2bqrf";
  })
  (fetchNuGet {
    pname = "System.Text.Json";
    version = "8.0.0";
    sha256 = "134savxw0sq7s448jnzw17bxcijsi1v38mirpbb6zfxmqlf04msw";
  })
  (fetchNuGet {
    pname = "UnitsNet";
    version = "5.31.0";
    sha256 = "16ay8hllrv3cxmw1nm1zx2iyrhxvbyckc35rlc4pfic0y125c41z";
  })
  (fetchNuGet {
    pname = "xunit";
    version = "2.7.0";
    sha256 = "0qs7yaz8qdhi75is7grgdxwxm09j36wv9c2ifyj2xd5jfzvlkc71";
  })
  (fetchNuGet {
    pname = "xunit.abstractions";
    version = "2.0.3";
    sha256 = "00wl8qksgkxld76fgir3ycc5rjqv1sqds6x8yx40927q5py74gfh";
  })
  (fetchNuGet {
    pname = "xunit.analyzers";
    version = "1.11.0";
    sha256 = "0qfmc6s5g2cnfvbdp837jvkgk1sq7hrql8bip6qjsy33liqwfx2m";
  })
  (fetchNuGet {
    pname = "xunit.assert";
    version = "2.7.0";
    sha256 = "14g5pvv709ykkz3lgqbdisksqfll72792fkrg4qr0s8jcp38kpyc";
  })
  (fetchNuGet {
    pname = "xunit.core";
    version = "2.7.0";
    sha256 = "0s31kxc383xa9132hz9nkm21d10xvay78yzpnz2pabaxld2mwdz9";
  })
  (fetchNuGet {
    pname = "xunit.extensibility.core";
    version = "2.7.0";
    sha256 = "0n4xc0fmj9a7rhsavs66n292g4vx5bsa27566k2g5dak4x1lvdv8";
  })
  (fetchNuGet {
    pname = "xunit.extensibility.execution";
    version = "2.7.0";
    sha256 = "1pmgl10wipvzq739gmlwdcmicpshb6620v1180p8yhham36ppy5i";
  })
  (fetchNuGet {
    pname = "xunit.runner.visualstudio";
    version = "2.5.7";
    sha256 = "07wan383cbxldlczjrxcn8s75jc7i2yv70s8sghv8n860mfsks96";
  })
]
