# This file was automatically generated by passthru.fetch-deps.
# Please dont edit it manually, your changes might get overwritten!

{ fetchNuGet }: [
  (fetchNuGet {
    pname = "Iot.Device.Bindings";
    version = "3.1.0";
    sha256 = "1985m18c6fhx8bnsigham9a5gijkw1ibdmnjicagf94cx5y90dvh";
  })
  (fetchNuGet {
    pname = "Microsoft.AspNetCore.App.Runtime.linux-arm64";
    version = "8.0.3";
    sha256 = "1s4lq0qiya5v73b5niipzmqkhj2d9wcb3nfaqlkbyjq660ahw98w";
  })
  (fetchNuGet {
    pname = "Microsoft.AspNetCore.App.Runtime.osx-arm64";
    version = "8.0.3";
    sha256 = "188bxir2v9rcfg036jmnczw3zlmf0kpy2f28jgbqli8ramlj5jq6";
  })
  (fetchNuGet {
    pname = "Microsoft.AspNetCore.App.Runtime.osx-x64";
    version = "8.0.3";
    sha256 = "0ri4jdv0v0pdwmvwgdzc46v43bd9d0xbbwscszqp8yd64dffs33v";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.ApiDescription.Server";
    version = "6.0.5";
    sha256 = "1pi2bm3cm0a7jzqzmfc2r7bpcdkmk3hhjfvb2c81j7wl7xdw3624";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging.Abstractions";
    version = "7.0.0";
    sha256 = "1gn7d18i1wfy13vrwhmdv1rmsb4vrk26kqdld4cgvh77yigj90xs";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App.Host.linux-arm64";
    version = "8.0.3";
    sha256 = "1ck7pky6ks5qq294vlqjvxrdpi70xc1g0yhank9kb3vmx9ixm9li";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App.Host.osx-arm64";
    version = "8.0.3";
    sha256 = "03qrqwd5v9rvc15i26ik1jxy670xm3gl5qv6mmk0ii1b6qw97ckp";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App.Host.osx-x64";
    version = "8.0.3";
    sha256 = "1bpx1fkyd9dpfjb70l4gh73qvin7rimfrx2hsi1m2amqjmx88s6j";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App.Runtime.linux-arm64";
    version = "8.0.3";
    sha256 = "19cbqcbsmx2mx88b6xhyh08r16bl0pjq1c5vgj5ai63phs6hlsjp";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App.Runtime.osx-arm64";
    version = "8.0.3";
    sha256 = "0jnd22x6hi16c8q7l74kh6iqvpl0cbny3fcrrpqky38685n5nzw5";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App.Runtime.osx-x64";
    version = "8.0.3";
    sha256 = "0gk6082rr0fm3dzspwdqfjzhsbi02iym28r4kcyiy1wcx83z7dfq";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.Platforms";
    version = "5.0.0";
    sha256 = "0mwpwdflidzgzfx2dlpkvvnkgkr2ayaf0s80737h4wa35gaj11rc";
  })
  (fetchNuGet {
    pname = "Microsoft.OpenApi";
    version = "1.2.3";
    sha256 = "07b19k89whj69j87afkz86gp9b3iybw8jqwvlgcn43m7fb2y99rr";
  })
  (fetchNuGet {
    pname = "Microsoft.Win32.Registry";
    version = "5.0.0";
    sha256 = "102hvhq2gmlcbq8y2cb7hdr2dnmjzfp2k3asr1ycwrfacwyaak7n";
  })
  (fetchNuGet {
    pname = "Microsoft.Win32.SystemEvents";
    version = "6.0.0";
    sha256 = "0c6pcj088g1yd1vs529q3ybgsd2vjlk5y1ic6dkmbhvrp5jibl9p";
  })
  (fetchNuGet {
    pname = "OpenCvSharp4";
    version = "4.9.0.20240103";
    sha256 = "15mfqkyf32d4whzcnvqig064r22y8wr4babfpr6l55pin8anvf0x";
  })
  (fetchNuGet {
    pname = "runtime.linux-arm.runtime.native.System.IO.Ports";
    version = "8.0.0";
    sha256 = "0qgrgf155mgsnakh0pxfg41zfwfn5as16g91q4k355v1nrvsi7wv";
  })
  (fetchNuGet {
    pname = "runtime.linux-arm64.runtime.native.System.IO.Ports";
    version = "8.0.0";
    sha256 = "1clc032fbynp9f8f57fh11lk6k8y7g0nlyb9nm44a0zpfkfcc1i2";
  })
  (fetchNuGet {
    pname = "runtime.linux-x64.runtime.native.System.IO.Ports";
    version = "8.0.0";
    sha256 = "0l623wmc1kswkv76fv15s2l35c3j2a4jvbv0v5jl6wz1466jx2p3";
  })
  (fetchNuGet {
    pname = "runtime.native.System.IO.Ports";
    version = "8.0.0";
    sha256 = "13w1w8f9ky7h7fkc2vamjv4vvs6b7nb3mcz9zgl3w7pk9xak3886";
  })
  (fetchNuGet {
    pname = "runtime.osx-arm64.runtime.native.System.IO.Ports";
    version = "8.0.0";
    sha256 = "08a88k2ps72206pigjq47r3xvp2j1ncmrr82bzgjskxj9kmhalx0";
  })
  (fetchNuGet {
    pname = "runtime.osx-x64.runtime.native.System.IO.Ports";
    version = "8.0.0";
    sha256 = "1wbdzmcmp2fczv4c3pzvdbap9mnzrm2hp3gclshx0cm7rc6psqkg";
  })
  (fetchNuGet {
    pname = "Swashbuckle.AspNetCore";
    version = "6.5.0";
    sha256 = "0k61chpz5j59s1yax28vx0mppx20ff8vg8grwja112hfrzj1f45n";
  })
  (fetchNuGet {
    pname = "Swashbuckle.AspNetCore.Swagger";
    version = "6.5.0";
    sha256 = "1s6axf6fin8sss3bvzp0s039rxrx71vx4rl559miw12bz3lld8kc";
  })
  (fetchNuGet {
    pname = "Swashbuckle.AspNetCore.SwaggerGen";
    version = "6.5.0";
    sha256 = "0hq93gy5vyrigpdk9lhqwxglxwkbxa8ydllwcqs4bwfcsspzrs83";
  })
  (fetchNuGet {
    pname = "Swashbuckle.AspNetCore.SwaggerUI";
    version = "6.5.0";
    sha256 = "17hx7kc187higm0gk67dndng3n7932sn3fwyj48l45cvyr3025h7";
  })
  (fetchNuGet {
    pname = "System.CodeDom";
    version = "5.0.0";
    sha256 = "14zs2wqkmdlxzj8ikx19n321lsbarx5vl2a8wrachymxn8zb5njh";
  })
  (fetchNuGet {
    pname = "System.Device.Gpio";
    version = "3.1.0";
    sha256 = "0ldv1njm5sf7bvchdn9549vmckhdm7iig718rcn1yf54pxaqf32b";
  })
  (fetchNuGet {
    pname = "System.Drawing.Common";
    version = "6.0.0";
    sha256 = "02n8rzm58dac2np8b3xw8ychbvylja4nh6938l5k2fhyn40imlgz";
  })
  (fetchNuGet {
    pname = "System.IO.Pipelines";
    version = "7.0.0";
    sha256 = "1ila2vgi1w435j7g2y7ykp2pdbh9c5a02vm85vql89az93b7qvav";
  })
  (fetchNuGet {
    pname = "System.IO.Ports";
    version = "8.0.0";
    sha256 = "113vfqanh1fbxx264db2z207qkm02x7mnr854igkc1xb8xrzvj0v";
  })
  (fetchNuGet {
    pname = "System.Management";
    version = "5.0.0";
    sha256 = "09hyv3p0zd549577clydlb2szl84m4gvdjnsry73n8b12ja7d75s";
  })
  (fetchNuGet {
    pname = "System.Memory";
    version = "4.5.5";
    sha256 = "08jsfwimcarfzrhlyvjjid61j02irx6xsklf32rv57x2aaikvx0h";
  })
  (fetchNuGet {
    pname = "System.Runtime.CompilerServices.Unsafe";
    version = "6.0.0";
    sha256 = "0qm741kh4rh57wky16sq4m0v05fxmkjjr87krycf5vp9f0zbahbc";
  })
  (fetchNuGet {
    pname = "System.Security.AccessControl";
    version = "5.0.0";
    sha256 = "17n3lrrl6vahkqmhlpn3w20afgz09n7i6rv0r3qypngwi7wqdr5r";
  })
  (fetchNuGet {
    pname = "System.Security.Principal.Windows";
    version = "5.0.0";
    sha256 = "1mpk7xj76lxgz97a5yg93wi8lj0l8p157a5d50mmjy3gbz1904q8";
  })
  (fetchNuGet {
    pname = "System.Text.Encodings.Web";
    version = "6.0.0";
    sha256 = "06n9ql3fmhpjl32g3492sj181zjml5dlcc5l76xq2h38c4f87sai";
  })
  (fetchNuGet {
    pname = "System.Text.Json";
    version = "6.0.1";
    sha256 = "0cxvkadvg0r0wh83k7677wvcjsfs2kifxvi7ia3ssvqplna2bqrf";
  })
  (fetchNuGet {
    pname = "UnitsNet";
    version = "5.31.0";
    sha256 = "16ay8hllrv3cxmw1nm1zx2iyrhxvbyckc35rlc4pfic0y125c41z";
  })
]
